module.exports = [
  require('./bind'),
  require('./rename'),
  require('./add'),
  require('./name'),
  require('./unbind'),
  require('./leaveFor'),
  require('./cancelLeaveFor'),
  require('./giveCard'),
  require('./cancelCard'),
  require('./cancelAbsence'),
  require('./cancelAllAbsence'),
  require('./testStart'),
  require('./testEnd'),
  require('./checkNow'),
  require('./moveMember'),
  require('./syncBindings'),
];
